title: BPM
description: Bioinformatics Project Manager documentation
remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true
url: https://chaochungkuo.github.io
baseurl: /BPM
plugins:
  - jekyll-remote-theme
aux_links:
  GitHub:
    - https://github.com/chaochungkuo/BPM

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  important:
    title: Important
    color: red
