name: Publish Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    # Strongly recommended: use an environment that matches PyPI's publisher config
    environment: pypi
    permissions:
      id-token: write   # REQUIRED for OIDC trusted publishing
      contents: read    # needed by actions/checkout

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: python -m pip install --upgrade build
      - run: python -m build          # creates dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # No username/password needed with trusted publishing